const express = require('express');
const path = require('path');
const app = express();
const PORT = process.env.PORT || 3000;

app.use(express.json({ limit: '50mb' }));
app.use(express.static(path.join(__dirname, 'public')));

// POST /api/parse - accepts base64-encoded .wbcat binary
app.post('/api/parse', (req, res) => {
  try {
      const { data } = req.body;
          if (!data) return res.status(400).json({ error: 'No data provided' });
              const buf = Buffer.from(data, 'base64');
                  const result = parseWbcat(buf);
                      res.json(result);
                        } catch (err) {
                            res.status(500).json({ error: err.message });
                              }
                              });

                              /**
                               * Parse a Windows Backup Catalog (.wbcat) binary file.
                                * The format is a sequence of tagged TLV (type-length-value) records.
                                 */
                                 function parseWbcat(buf) {
                                   const result = {
                                       fileSize: buf.length,
                                           magic: buf.slice(0, 4).toString('hex'),
                                               records: [],
                                                   summary: {}
                                                     };

                                                       // Known WBCAT signatures
                                                         const MAGIC_WBCAT = '4d534446'; // "MSDF" - Microsoft Data Format
                                                           if (result.magic !== MAGIC_WBCAT) {
                                                               // Still try to parse, just note the magic
                                                                   result.warning = `Unexpected magic: ${result.magic} (expected 4d534446)`;
                                                                     }

                                                                       // Parse header fields at fixed offsets
                                                                         if (buf.length >= 8) {
                                                                             result.version = buf.readUInt32LE(4);
                                                                               }
                                                                                 if (buf.length >= 16) {
                                                                                     result.catalogType = buf.readUInt32LE(8);
                                                                                         result.flags = buf.readUInt32LE(12);
                                                                                           }

                                                                                             // Scan for GUID patterns (16-byte sequences matching GUID heuristic)
                                                                                               const guids = extractGuids(buf);
                                                                                                 result.guids = guids;

                                                                                                   // Scan for Unicode strings
                                                                                                     const strings = extractUnicodeStrings(buf);
                                                                                                       result.strings = strings;
                                                                                                       
                                                                                                         // Scan for timestamps (Windows FILETIME: 64-bit LE, 100-ns intervals since 1601-01-01)
                                                                                                           const timestamps = extractTimestamps(buf);
                                                                                                             result.timestamps = timestamps;
                                                                                                             
                                                                                                               // Scan for volume/disk records by looking for known patterns
                                                                                                                 result.records = scanRecords(buf);
                                                                                                                 
                                                                                                                   // Build summary
                                                                                                                     result.summary = {
                                                                                                                         totalSize: `${(buf.length / 1024).toFixed(1)} KB`,
                                                                                                                             guidCount: guids.length,
                                                                                                                                 stringCount: strings.length,
                                                                                                                                     timestampCount: timestamps.length,
                                                                                                                                         recordCount: result.records.length
                                                                                                                                           };
                                                                                                                                           
                                                                                                                                             return result;
                                                                                                                                             }
                                                                                                                                             
                                                                                                                                             function extractGuids(buf) {
                                                                                                                                               const guids = [];
                                                                                                                                                 const seen = new Set();
                                                                                                                                                   for (let i = 0; i <= buf.length - 16; i++) {
                                                                                                                                                       // Simple heuristic: look for 16-byte sequences that look like GUIDs
                                                                                                                                                           // A GUID has specific structural properties; we check for non-null bytes
                                                                                                                                                               const slice = buf.slice(i, i + 16);
                                                                                                                                                                   const hex = slice.toString('hex');
                                                                                                                                                                       if (seen.has(hex)) continue;
                                                                                                                                                                           // Check if this could be a meaningful GUID (not all zeros, not all ones)
                                                                                                                                                                               const nonZero = slice.filter(b => b !== 0).length;
                                                                                                                                                                                   if (nonZero >= 8 && nonZero <= 15) {
                                                                                                                                                                                         // Format as GUID: {XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX}
                                                                                                                                                                                               const g = formatGuid(slice);
                                                                                                                                                                                                     if (!seen.has(g)) {
                                                                                                                                                                                                             seen.add(g);
                                                                                                                                                                                                                     guids.push({ offset: `0x${i.toString(16).padStart(8, '0')}`, guid: g });
                                                                                                                                                                                                                             if (guids.length >= 20) break;
                                                                                                                                                                                                                                   }
                                                                                                                                                                                                                                       }
                                                                                                                                                                                                                                         }
                                                                                                                                                                                                                                           return guids;
                                                                                                                                                                                                                                           }
                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                           function formatGuid(bytes) {
                                                                                                                                                                                                                                             const h = bytes.toString('hex');
                                                                                                                                                                                                                                               return `{${h.slice(0,8)}-${h.slice(8,12)}-${h.slice(12,16)}-${h.slice(16,20)}-${h.slice(20,32)}}`.toUpperCase();
                                                                                                                                                                                                                                               }
                                                                                                                                                                                                                                               
                                                                                                                                                                                                                                               function extractUnicodeStrings(buf) {
                                                                                                                                                                                                                                                 const strings = [];
                                                                                                                                                                                                                                                   let i = 0;
                                                                                                                                                                                                                                                     while (i < buf.length - 4) {
                                                                                                                                                                                                                                                         // Look for UTF-16LE strings: sequences of ASCII chars with null byte between
                                                                                                                                                                                                                                                             let start = i;
                                                                                                                                                                                                                                                                 let len = 0;
                                                                                                                                                                                                                                                                     while (i + 1 < buf.length) {
                                                                                                                                                                                                                                                                           const lo = buf[i];
                                                                                                                                                                                                                                                                                 const hi = buf[i + 1];
                                                                                                                                                                                                                                                                                       if (hi === 0 && lo >= 0x20 && lo <= 0x7E) {
                                                                                                                                                                                                                                                                                               len++;
                                                                                                                                                                                                                                                                                                       i += 2;
                                                                                                                                                                                                                                                                                                             } else {
                                                                                                                                                                                                                                                                                                                     break;
                                                                                                                                                                                                                                                                                                                           }
                                                                                                                                                                                                                                                                                                                               }
                                                                                                                                                                                                                                                                                                                                   if (len >= 4) {
                                                                                                                                                                                                                                                                                                                                         const str = buf.slice(start, start + len * 2).toString('utf16le');
                                                                                                                                                                                                                                                                                                                                               strings.push({
                                                                                                                                                                                                                                                                                                                                                       offset: `0x${start.toString(16).padStart(8, '0')}`,
                                                                                                                                                                                                                                                                                                                                                               value: str
                                                                                                                                                                                                                                                                                                                                                                     });
                                                                                                                                                                                                                                                                                                                                                                         } else {
                                                                                                                                                                                                                                                                                                                                                                               i = start + 1;
                                                                                                                                                                                                                                                                                                                                                                                   }
                                                                                                                                                                                                                                                                                                                                                                                       if (strings.length >= 50) break;
                                                                                                                                                                                                                                                                                                                                                                                         }
                                                                                                                                                                                                                                                                                                                                                                                           return strings;
                                                                                                                                                                                                                                                                                                                                                                                           }
                                                                                                                                                                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                                                                                                                                                                           function extractTimestamps(buf) {
                                                                                                                                                                                                                                                                                                                                                                                             const timestamps = [];
                                                                                                                                                                                                                                                                                                                                                                                               // Windows FILETIME epoch offset from Unix epoch in ms
                                                                                                                                                                                                                                                                                                                                                                                                 const EPOCH_DIFF = 11644473600000;
                                                                                                                                                                                                                                                                                                                                                                                                   for (let i = 0; i <= buf.length - 8; i += 4) {
                                                                                                                                                                                                                                                                                                                                                                                                       // Read 64-bit LE value
                                                                                                                                                                                                                                                                                                                                                                                                           const lo = buf.readUInt32LE(i);
                                                                                                                                                                                                                                                                                                                                                                                                               const hi = buf.readUInt32LE(i + 4);
                                                                                                                                                                                                                                                                                                                                                                                                                   const val = hi * 0x100000000 + lo;
                                                                                                                                                                                                                                                                                                                                                                                                                       // Convert 100-ns intervals to ms
                                                                                                                                                                                                                                                                                                                                                                                                                           const ms = val / 10000 - EPOCH_DIFF;
                                                                                                                                                                                                                                                                                                                                                                                                                               // Filter for plausible dates: 2000 to 2040
                                                                                                                                                                                                                                                                                                                                                                                                                                   const year = new Date(ms).getFullYear();
                                                                                                                                                                                                                                                                                                                                                                                                                                       if (year >= 2000 && year <= 2040) {
                                                                                                                                                                                                                                                                                                                                                                                                                                             const dt = new Date(ms).toISOString();
                                                                                                                                                                                                                                                                                                                                                                                                                                                   timestamps.push({
                                                                                                                                                                                                                                                                                                                                                                                                                                                           offset: `0x${i.toString(16).padStart(8, '0')}`,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                   timestamp: dt
                                                                                                                                                                                                                                                                                                                                                                                                                                                                         });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                               if (timestamps.length >= 20) break;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       return timestamps;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       function scanRecords(buf) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         const records = [];
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           // Look for common record type patterns (4-byte type + 4-byte length TLV)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             for (let i = 0; i <= buf.length - 8; i++) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 const type = buf.readUInt32LE(i);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     const len = buf.readUInt32LE(i + 4);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         // Plausible record: type in a known range, length fits within buffer
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             if (type > 0 && type < 0xFFFF && len > 0 && len < 0x10000 && i + 8 + len <= buf.length) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   const data = buf.slice(i + 8, i + 8 + Math.min(len, 64)).toString('hex');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         records.push({
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 offset: `0x${i.toString(16).padStart(8, '0')}`,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         type: `0x${type.toString(16).padStart(4, '0')}`,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 length: len,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         preview: data
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     i += 7 + len; // advance past this record
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           if (records.length >= 30) break;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   return records;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   app.listen(PORT, () => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     console.log(`wbcat-viewer running on http://localhost:${PORT}`);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     });
